// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kchristidis/nested/extended/extended.proto

/*
Package extended is a generated protocol buffer package.

It is generated from these files:
	github.com/kchristidis/nested/extended/extended.proto

It has these top-level messages:
	Response
*/
package extended

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/kchristidis/nested/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response struct {
	// Types that are valid to be assigned to Type:
	//	*Response_Common
	//	*Response_Baz
	Type isResponse_Type `protobuf_oneof:"Type"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isResponse_Type interface {
	isResponse_Type()
}

type Response_Common struct {
	Common *common.Response `protobuf:"bytes,1,opt,name=common,oneof"`
}
type Response_Baz struct {
	Baz int32 `protobuf:"varint,2,opt,name=baz,oneof"`
}

func (*Response_Common) isResponse_Type() {}
func (*Response_Baz) isResponse_Type()    {}

func (m *Response) GetType() isResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Response) GetCommon() *common.Response {
	if x, ok := m.GetType().(*Response_Common); ok {
		return x.Common
	}
	return nil
}

func (m *Response) GetBaz() int32 {
	if x, ok := m.GetType().(*Response_Baz); ok {
		return x.Baz
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_Common)(nil),
		(*Response_Baz)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// Type
	switch x := m.Type.(type) {
	case *Response_Common:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Common); err != nil {
			return err
		}
	case *Response_Baz:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Baz))
	case nil:
	default:
		return fmt.Errorf("Response.Type has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 1: // Type.common
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(common.Response)
		err := b.DecodeMessage(msg)
		m.Type = &Response_Common{msg}
		return true, err
	case 2: // Type.baz
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Type = &Response_Baz{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// Type
	switch x := m.Type.(type) {
	case *Response_Common:
		s := proto.Size(x.Common)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Baz:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Baz))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Response)(nil), "extended.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Get service

type GetClient interface {
	Get(ctx context.Context, in *common.Request, opts ...grpc.CallOption) (*Response, error)
}

type getClient struct {
	cc *grpc.ClientConn
}

func NewGetClient(cc *grpc.ClientConn) GetClient {
	return &getClient{cc}
}

func (c *getClient) Get(ctx context.Context, in *common.Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/extended.Get/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Get service

type GetServer interface {
	Get(context.Context, *common.Request) (*Response, error)
}

func RegisterGetServer(s *grpc.Server, srv GetServer) {
	s.RegisterService(&_Get_serviceDesc, srv)
}

func _Get_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/extended.Get/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetServer).Get(ctx, req.(*common.Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Get_serviceDesc = grpc.ServiceDesc{
	ServiceName: "extended.Get",
	HandlerType: (*GetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Get_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/kchristidis/nested/extended/extended.proto",
}

func init() {
	proto.RegisterFile("github.com/kchristidis/nested/extended/extended.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4d, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x4e, 0xce, 0x28, 0xca, 0x2c, 0x2e, 0xc9, 0x4c,
	0xc9, 0x2c, 0xd6, 0xcf, 0x4b, 0x2d, 0x2e, 0x49, 0x4d, 0xd1, 0x4f, 0xad, 0x28, 0x49, 0xcd, 0x4b,
	0x41, 0x62, 0xe8, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x71, 0xc0, 0xf8, 0x52, 0x86, 0xf8, 0x0d,
	0x48, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x52, 0x10, 0xcd, 0x4a, 0x41, 0x5c, 0x1c, 0x41, 0xa9,
	0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x5a, 0x5c, 0x6c, 0x10, 0x39, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0x6e, 0x23, 0x01, 0x3d, 0xa8, 0x52, 0x98, 0x0a, 0x0f, 0x86, 0x20, 0xa8, 0x0a, 0x21, 0x21,
	0x2e, 0xe6, 0xa4, 0xc4, 0x2a, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x56, 0x0f, 0x86, 0x20, 0x10, 0xc7,
	0x89, 0x8d, 0x8b, 0x25, 0xa4, 0xb2, 0x20, 0xd5, 0xc8, 0x90, 0x8b, 0xd9, 0x3d, 0xb5, 0x44, 0x48,
	0x0b, 0x42, 0xf1, 0x23, 0x4c, 0x29, 0x2c, 0x4d, 0x2d, 0x2e, 0x91, 0x12, 0xd2, 0x83, 0x7b, 0x00,
	0x66, 0x70, 0x12, 0x1b, 0xd8, 0x35, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0xce, 0xb0,
	0x9a, 0x03, 0x01, 0x00, 0x00,
}
